FROM node:20-slim

WORKDIR /app

COPY package.json yarn.lock tsconfig.json ./
RUN yarn install --frozen-lockfile

COPY scripts ./scripts
COPY assets/rds-ca-bundle.pem ./rds-ca-bundle.pem

ENV NODE_EXTRA_CA_CERTS=/app/rds-ca-bundle.pem

ENTRYPOINT ["./node_modules/.bin/ts-node"]
CMD ["scripts/seed-db.ts"]
